version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: 
          name: "Install Firebase"
          command: sudo npm install -g firebase-tools
      - run: 
          name: "Deploy to Firebase"
          command: npm run deploy

# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - build